# Custom Language File for Launcher Customizer

[ejs.app]
title = "Prestige Town"

[ejs.landing]
mediaGitHubURL = "https://github.com/EchoBump/PrestigeTownRP"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/xrBdVQteAc"

[ejs.settings]
sourceGithubLink = "https://github.com/EchoBump/PrestigeTownRP"
supportLink = "https://github.com/EchoBump/PrestigeTownRP/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR PRESTIGE TOWN"
welcomeDescription = "Inspiré du projet Crazy Town de Mastu et recréé par ByLo, Prestige Town est un savant mélange de survie, d'événements absurdes, de roleplay pas toujours très sérieux, et surtout d’une bonne dose de fun entre potes. Construisez, trollez, jouez votre vie (ou pas) et rejoignez une communauté qui a clairement raté son jet de sagesse. Ici, c’est n’importe quoi… mais dans le bon sens."
welcomeDescCTA = "Allez viens, on est (presque) sérieux ici."
