[ejs.landing]
updateAvailableTooltip = "Mise à jour disponible"
usernamePlaceholder = "Nom d'utilisateur"
usernameEditButton = "Modifier"
settingsTooltip = "Paramètres"
serverStatus = "SERVEUR"
serverStatusPlaceholder = "HORS LIGNE"
mojangStatus = "STATUT MOJANG"
mojangStatusTooltipTitle = "Services"
mojangStatusNETitle = "Non&nbsp;essentiels"
newsButton = "ACTUALITÉS"
launchButton = "JOUER"
launchButtonPlaceholder = "&#8226; Aucun serveur sélectionné"
launchDetails = "Veuillez patienter.."
newsNavigationStatus = "{currentPage} sur {totalPages}"
newsErrorLoadSpan = "Vérification des actualités.."
newsErrorFailedSpan = "Échec du chargement des actualités"
newsErrorRetryButton = "Réessayer"
newsErrorNoneSpan = "Aucune actualité"

[ejs.login]
loginCancelText = "Annuler"
loginSubheader = "CONNEXION MINECRAFT"
loginEmailError = "* Valeur invalide"
loginEmailPlaceholder = "EMAIL OU NOM D'UTILISATEUR"
loginPasswordError = "* Requis"
loginPasswordPlaceholder = "MOT DE PASSE"
loginForgotPasswordLink = "https://minecraft.net/password/forgot/"
loginForgotPasswordText = "mot de passe oublié ?"
loginRememberMeText = "se souvenir de moi ?"
loginButtonText = "CONNEXION"
loginNeedAccountLink = "https://minecraft.net/store/minecraft-java-edition/"
loginNeedAccountText = "Besoin d'un compte ?"
loginPasswordDisclaimer1 = "Votre mot de passe est envoyé directement à Mojang et jamais stocké."
loginPasswordDisclaimer2 = "{appName} n'est pas affilié à Mojang AB."

[ejs.loginOptions]
loginOptionsTitle = "Options de connexion"
loginWithMicrosoft = "Se connecter avec Microsoft"
loginWithMojang = "Se connecter avec Mojang"
cancelButton = "Annuler"

[ejs.overlay]
serverSelectHeader = "Serveurs disponibles"
serverSelectConfirm = "Sélectionner"
serverSelectCancel = "Annuler"
accountSelectHeader = "Sélectionner un compte"
accountSelectConfirm = "Sélectionner"
accountSelectCancel = "Annuler"

[ejs.settings]
navHeaderText = "Paramètres"
navAccount = "Compte"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Lanceur"
navAbout = "À propos"
navUpdates = "Mises à jour"
navDone = "Terminé"
tabAccountHeaderText = "Paramètres du compte"
tabAccountHeaderDesc = "Ajoutez de nouveaux comptes ou gérez les comptes existants."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Ajouter un compte Microsoft"
mojangAccount = "Mojang"
addMojangAccount = "+ Ajouter un compte Mojang"
minecraftTabHeaderText = "Paramètres Minecraft"
minecraftTabHeaderDesc = "Options relatives au lancement du jeu."
gameResolutionTitle = "Résolution du jeu"
launchFullscreenTitle = "Lancer en plein écran."
autoConnectTitle = "Se connecter automatiquement au serveur au lancement."
launchDetachedTitle = "Lancer le processus de jeu indépendamment du lanceur."
launchDetachedDesc = "Si le jeu n'est pas détaché, fermer le lanceur fermera également le jeu."
tabModsHeaderText = "Paramètres des mods"
tabModsHeaderDesc = "Activer ou désactiver les mods."
switchServerButton = "Changer"
requiredMods = "Mods requis"
optionalMods = "Mods optionnels"
dropinMods = "Mods additionnels"
addMods = "Ajouter des mods"
dropinRefreshNote = "(F5 pour actualiser)"
shaderpacks = "Packs de shaders"
shaderpackDesc = "Activez ou désactivez les shaders. Notez que les shaders ne fonctionnent correctement que sur des configurations puissantes. Vous pouvez ajouter des packs personnalisés ici."
selectShaderpack = "Sélectionner un pack de shaders"
tabJavaHeaderText = "Paramètres Java"
tabJavaHeaderDesc = "Gérer la configuration Java (avancé)."
memoryTitle = "Mémoire"
maxRAM = "RAM maximale"
minRAM = "RAM minimale"
memoryDesc = "La RAM minimale recommandée est de 3 gigaoctets. Définir des valeurs identiques pour le minimum et le maximum peut réduire les saccades."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponible"
javaExecutableTitle = "Exécutable Java"
javaExecSelDialogTitle = "Sélectionner l'exécutable Java"
javaExecSelButtonText = "Choisir un fichier"
javaExecDesc = "L'exécutable Java est validé avant le lancement du jeu."
javaPathDesc = "Le chemin doit se terminer par <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Options JVM supplémentaires"
jvmOptsDesc = "Options à fournir à la JVM lors de l'exécution. <em>-Xms</em> et <em>-Xmx</em> ne doivent pas être inclus."
launcherTabHeaderText = "Paramètres du lanceur"
launcherTabHeaderDesc = "Options relatives au lanceur lui-même."
allowPrereleaseTitle = "Autoriser les préversions."
allowPrereleaseDesc = "Les préversions incluent de nouvelles fonctionnalités qui n'ont pas été entièrement testées ou intégrées.<br>Ce sera toujours vrai si vous utilisez une version préliminaire."
dataDirectoryTitle = "Répertoire des données"
selectDataDirectory = "Sélectionner le répertoire des données"
chooseFolder = "Choisir un dossier"
dataDirectoryDesc = "Tous les fichiers du jeu et les installations Java locales seront stockés dans le répertoire de données.<br>Les captures d'écran et les sauvegardes de monde sont stockées dans le dossier d'instance pour la configuration du serveur correspondante."
aboutTabHeaderText = "À propos"
aboutTabHeaderDesc = "Afficher les informations et les notes de version pour la version actuelle."
aboutTitle = "{appName}"
stableRelease = "Version stable"
versionText = "Version "
sourceGithub = "Code source (GitHub)"
support = "Support"
devToolsConsole = "Console DevTools"
releaseNotes = "Notes de version"
changelog = "Journal des modifications"
noReleaseNotes = "Aucune note de version"
viewReleaseNotes = "Voir les notes de version sur GitHub"
launcherUpdatesHeaderText = "Mises à jour du lanceur"
launcherUpdatesHeaderDesc = "Télécharger, installer et consulter les mises à jour du lanceur."
checkForUpdates = "Vérifier les mises à jour"
whatsNew = "Nouveautés"
updateReleaseNotes = "Notes de version de la mise à jour"

[ejs.waiting]
waitingText = "En attente de Microsoft.."

[ejs.welcome]
continueButton = "CONTINUER"

[js.discord]
waiting = "En attente du client.."
state = "Serveur : {shortId}"

[js.index]
microsoftLoginTitle = "Connexion Microsoft"
microsoftLogoutTitle = "Déconnexion Microsoft"

[js.login]
login = "CONNEXION"
loggingIn = "CONNEXION EN COURS"
success = "SUCCÈS"
tryAgain = "Réessayer"

[js.login.error]
invalidValue = "* Valeur invalide"
requiredValue = "* Requis"

[js.login.error.unknown]
title = "Erreur inconnue lors de la connexion"
desc = "Une erreur inconnue s'est produite. Veuillez consulter la console pour plus de détails."

[js.landing.launch]
pleaseWait = "Veuillez patienter.."
failureTitle = "Erreur lors du lancement"
failureText = "Voir la console (CTRL + Maj + i)"
okay = "OK"

[js.landing.selectedAccount]
noAccountSelected = "Aucun compte sélectionné"

[js.landing.selectedServer]
noSelection = "Aucun serveur sélectionné"
loading = "Chargement..."

[js.landing.serverStatus]
server = "SERVEUR"
offline = "HORS LIGNE"
players = "JOUEURS"

[js.landing.systemScan]
checking = "Analyse du système en cours..."
noCompatibleJava = "Aucune installation<br>Java compatible trouvée"
installJavaMessage = "Pour lancer Minecraft, vous avez besoin d'une installation Java {major} en 64 bits. Voulez-vous qu'on l'installe pour vous ?"
installJava = "Installer Java"
installJavaManually = "Installer manuellement"
javaDownloadPrepare = "Préparation du téléchargement de Java..."
javaDownloadFailureTitle = "Erreur lors du téléchargement de Java"
javaDownloadFailureText = "Voir la console (CTRL + Maj + i) pour plus de détails."
javaRequired = "Java est requis<br>pour lancer"
javaRequiredMessage = 'Une installation valide de Java {major} x64 est requise pour le lancement.<br><br>Consultez notre <a href="https://github.com/dscalzi/HeliosLauncher/wiki/Java-Management#manually-installing-a-valid-version-of-java">guide d’installation de Java</a> pour plus d’infos.'
javaRequiredDismiss = "J'ai compris"
javaRequiredCancel = "Retour"

[js.landing.downloadJava]
findJdkFailure = "Échec lors de la recherche d’une distribution OpenJDK."
javaDownloadCorruptedError = "Le JDK téléchargé est corrompu (hash incorrect)."
extractingJava = "Extraction de Java"
javaInstalled = "Java installé !"

[js.landing.dlAsync]
loadingServerInfo = "Chargement des infos serveur..."
fatalError = "Erreur critique"
unableToLoadDistributionIndex = "Impossible de charger l’index de distribution. Voir la console (CTRL + Maj + i) pour plus de détails."
pleaseWait = "Veuillez patienter..."
errorDuringLaunchTitle = "Erreur lors du lancement"
seeConsoleForDetails = "Voir la console (CTRL + Maj + i) pour plus de détails."
validatingFileIntegrity = "Vérification de l’intégrité des fichiers..."
errorDuringFileVerificationTitle = "Erreur lors de la vérification des fichiers"
downloadingFiles = "Téléchargement des fichiers..."
errorDuringFileDownloadTitle = "Erreur lors du téléchargement des fichiers"
preparingToLaunch = "Préparation du lancement..."
launchingGame = "Lancement du jeu..."
launchWrapperNotDownloaded = "Le fichier principal LaunchWrapper n’a pas pu être téléchargé. Le jeu ne peut donc pas se lancer.<br><br>Pour corriger cela, désactivez temporairement votre antivirus et relancez le jeu.<br><br>Si vous avez le temps, merci de <a href=\"https://github.com/dscalzi/HeliosLauncher/issues\">signaler le problème</a> en indiquant l’antivirus utilisé."
doneEnjoyServer = "C’est prêt. Amusez-vous bien !"
checkConsoleForDetails = "Consultez la console (CTRL + Maj + i) pour plus d'infos."

[js.landing.news]
checking = "Recherche d’actualités"

[js.landing.discord]
loading = "Chargement du jeu..."
joining = "En route pour Westeros !"
joined = "Exploration du royaume !"

[js.overlay]
dismiss = "Fermer"

[js.settings.fileSelectors]
executables = "Exécutables"
allFiles = "Tous les fichiers"

[js.settings.mstfLogin]
errorTitle = "Une erreur s’est produite"
errorMessage = "L’authentification Microsoft a échoué. Veuillez réessayer."
okButton = "OK"

[js.settings.mstfLogout]
errorTitle = "Une erreur s’est produite"
errorMessage = "La déconnexion Microsoft a échoué. Veuillez réessayer."
okButton = "OK"

[js.settings.authAccountSelect]
selectButton = "Choisir ce compte"
selectedButton = "Compte sélectionné &#10004;"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Attention<br>C’est votre dernier compte"
lastAccountWarningMessage = "Vous devez être connecté à au moins un compte pour utiliser le launcher. Vous devrez vous reconnecter ensuite.<br><br>Voulez-vous vraiment vous déconnecter ?"
confirmButton = "Oui, continuer"
cancelButton = "Annuler"

[js.settings.authAccountPopulate]
username = "Nom d’utilisateur"
uuid = "UUID"
selectAccount = "Sélectionner"
selectedAccount = "Compte sélectionné ✓"
logout = "Se déconnecter"

[js.settings.dropinMods]
removeButton = "Retirer"
deleteFailedTitle = "Échec de la suppression<br>du mod {fullName}"
deleteFailedMessage = "Assurez-vous que le fichier n’est pas utilisé et réessayez."
failedToggleTitle = "Impossible d’activer/désactiver<br>un ou plusieurs mods"
okButton = "OK"

[js.settings.serverListing]
mainServer = "Serveur principal"

[js.settings.java]
selectedJava = "Sélectionné : Java {version} ({vendor})"
invalidSelection = "Sélection invalide"
requiresJava = "Nécessite Java {major} x64."
availableOptions = "Options disponibles pour Java {major} (HotSpot VM)"

[js.settings.about]
preReleaseTitle = "Préversion"
stableReleaseTitle = "Version stable"
releaseNotesFailed = "Impossible de charger les notes de version."

[js.settings.updates]
newReleaseTitle = "Nouvelle version disponible"
newPreReleaseTitle = "Nouvelle préversion disponible"
downloadingButton = "Téléchargement..."
downloadButton = 'Télécharger depuis GitHub<span style="font-size: 10px;color: gray;text-shadow: none !important;">Fermez le launcher puis lancez le fichier .dmg pour mettre à jour.</span>'
latestVersionTitle = "Vous utilisez la dernière version"
checkForUpdatesButton = "Rechercher les mises à jour"
checkingForUpdatesButton = "Recherche de mises à jour..."

[js.settings.msftLogin]
errorTitle = "Échec de la connexion Microsoft"
errorMessage = "Impossible de vous authentifier avec votre compte Microsoft. Veuillez réessayer."
okButton = "OK"

[js.uibinder.startup]
fatalErrorTitle = "Erreur critique : Impossible de charger l’index de distribution"
fatalErrorMessage = "Connexion impossible aux serveurs pour télécharger l’index de distribution. Aucune copie locale disponible.<br><br>Ce fichier est essentiel pour obtenir les dernières infos serveur. Le launcher ne peut pas démarrer sans lui. Vérifiez votre connexion et relancez l’application."
closeButton = "Fermer"

[js.uibinder.validateAccount]
failedMessageTitle = "Échec du renouvellement de connexion"
failedMessage = "Impossible de renouveler la connexion pour <strong>{account}</strong>. Veuillez sélectionner un autre compte ou vous reconnecter."
failedMessageSelectAnotherAccount = "Impossible de renouveler la connexion pour <strong>{account}</strong>. Veuillez vous reconnecter."
loginButton = "Connexion"
selectAnotherAccountButton = "Choisir un autre compte"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Recherche de mise à jour..."
installNowButton = "Installer maintenant"
checkForUpdatesButton = "Rechercher des mises à jour"

[js.auth.microsoft.error]
noProfileTitle = "Erreur de connexion :<br>Profil non configuré"
noProfileDesc = "Votre compte Microsoft n’a pas encore de profil Minecraft. Si vous avez acheté ou activé le jeu récemment via le Xbox Game Pass, vous devez créer un profil sur <a href=\"https://minecraft.net/\">Minecraft.net</a>.<br><br>Si vous n’avez pas encore acheté le jeu, vous pouvez le faire sur le même site."
noXboxAccountTitle = "Erreur de connexion :<br>Pas de compte Xbox"
noXboxAccountDesc = "Aucun compte Xbox n’est lié à ce compte Microsoft."
xblBannedTitle = "Erreur de connexion :<br>Xbox Live non disponible"
xblBannedDesc = "Votre compte Microsoft est d’un pays où Xbox Live est indisponible ou interdit."
under18Title = "Erreur de connexion :<br>Autorisation parentale requise"
under18Desc = "Les comptes de moins de 18 ans doivent être ajoutés à une famille par un adulte."
unknownTitle = "Erreur inconnue lors de la connexion"
unknownDesc = "Une erreur inconnue est survenue. Consultez la console pour plus d’informations."

[js.auth.mojang.error]
methodNotAllowedTitle = "Erreur interne :<br>Méthode non autorisée"
methodNotAllowedDesc = "Méthode non autorisée. Merci de signaler cette erreur."
notFoundTitle = "Erreur interne :<br>Introuvable"
notFoundDesc = "Le point de terminaison d’authentification est introuvable. Merci de signaler ce problème."
accountMigratedTitle = "Erreur de connexion :<br>Compte migré"
accountMigratedDesc = "Vous avez essayé de vous connecter avec un compte migré. Utilisez l’e-mail comme identifiant."
invalidCredentialsTitle = "Erreur de connexion :<br>Identifiants invalides"
invalidCredentialsDesc = "L’adresse ou le mot de passe est incorrect. Veuillez réessayer."
tooManyAttemptsTitle = "Erreur de connexion :<br>Trop de tentatives"
tooManyAttemptsDesc = "Trop de tentatives récentes avec ce compte. Réessayez plus tard."
invalidTokenTitle = "Erreur de connexion :<br>Jeton invalide"
invalidTokenDesc = "Le jeton d’accès fourni est invalide."
tokenHasProfileTitle = "Erreur de connexion :<br>Profil déjà lié"
tokenHasProfileDesc = "Le jeton a déjà un profil. La sélection de profil n’est pas encore gérée."
credentialsMissingTitle = "Erreur de connexion :<br>Identifiants manquants"
credentialsMissingDesc = "Nom d’utilisateur ou mot de passe manquant, ou mot de passe trop court."
invalidSaltVersionTitle = "Erreur de connexion :<br>Version de sel invalide"
invalidSaltVersionDesc = "Version de sel invalide."
unsupportedMediaTypeTitle = "Erreur interne :<br>Type de média non supporté"
unsupportedMediaTypeDesc = "Type de média non supporté. Merci de signaler cette erreur."
accountGoneTitle = "Erreur de connexion :<br>Compte migré"
accountGoneDesc = "Ce compte a été migré vers Microsoft. Connectez-vous avec Microsoft."
unreachableTitle = "Erreur de connexion :<br>Serveur inaccessible"
unreachableDesc = "Impossible d’accéder aux serveurs d’authentification. Vérifiez votre connexion Internet."
gameNotPurchasedTitle = "Erreur de connexion :<br>Jeu non acheté"
gameNotPurchasedDesc = "Ce compte n’a pas acheté Minecraft. Vous pouvez l’acheter sur <a href=\"https://minecraft.net/\">Minecraft.net</a>"
unknownErrorTitle = "Erreur inconnue lors de la connexion"
unknownErrorDesc = "Une erreur inconnue est survenue. Consultez la console pour plus d’informations."
